script/console, server client/server at once

diff --git a/script/console b/script/console
--- a/script/console
+++ b/script/console
@@ -11,10 +11,10 @@ function main {
   cd "$shome"
   case "${1:-}" in
     default)
-      exec node "$shome/resources/public/js/server/server.js"
+      exec lein figwheel client server
       ;;
     *)
-      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
+      echo "ERROR: unknown console command: ${1:-/not-supplied/}" 1>&2
       return 1
       ;;
   esac
